language: node_js
sudo: false
cache:
  directories:
    - node_modules

node_js:
  - 8
  - 10
  - 12
  - node

matrix:
  include:
    - name: Lint
      node_js: 12
      script: npm run lint

script: npm run ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
